### ISSUE TITLE
Error when trying to publish node with language variant whose URL cannot be generated

### ISSUE THREAD

**Issue by davidzweben** [Gibe/Umbraco.Community.FrontDoorCache#6]
When a node has a language variant whose URL cannot be determined by Umbraco, attempting to publish any variant of this node results in the error message listed below.

This happens when a language variant exists for which there is no corresponding "Culture and Hostnames" configuration on an ancestor node or self, **and/or** when a node has unpublished ancestors for any of its language variants. In these scenarios, the node shows a message under Info > Links, either "This document is published but is not in the cache" or "This culture is published but is not visible because it is unpublished on parent [parent name]". It appears that publishing still succeeds for the variants whose URL could be determined.

It makes sense that the cache cannot be cleared for these un-publishable variants, however the error should not occur when publishing an unaffected language variant on an affected node, and a more descriptive error message would help.

```
Received an error from the server
An error occurred

One or more errors occurred. (One or more errors occurred. (Invalid URI: The hostname could not be parsed.))
Exception Details
System.AggregateException, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: One or more errors occurred. (One or more errors occurred. (Invalid URI: The hostname could not be parsed.)) 
```

```
Stacktrace

at Umbraco.Cms.Infrastructure.Scoping.Scope.TryFinally(Action[] actions)

   at Umbraco.Cms.Infrastructure.Scoping.Scope.Dispose()

   at Umbraco.Cms.Core.Services.ContentService.SaveAndPublish(IContent content, String[] cultures, Int32 userId)

   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PublishInternal(ContentItemSave contentItem, String defaultCulture, String cultureForInvariantErrors, Boolean& wasCancelled, String[]& successfulCultures)

   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSaveInternal[TVariant](ContentItemSave contentItem, Func`3 saveMethod, Func`2 mapToDisplay)

   at Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSave(ContentItemSave contentItem)

   at lambda_method1834(Closure, Object)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)


```

**Comment by stevetemple** [comment]
I think this will be fixed by #7
